name: pytest

on:
  pull_request:
    branches: ["main"]
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "tests/**"

jobs:
  pytest-on-pull:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: "Run tests"
      run: docker build -t test --target test . && docker run --rm -it test
