name: pytest

on:
  pull_request:
    branches: ["main"]
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "tests/**"

jobs:
  pytest-on-pull:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: pip

    - name: Install Python libraries
      run: |
        pip install --user -r requirements.txt
        pip install --user -r tests/requirements.txt

    - name: "Run tests"
      run: cd tests && pytest -v -s -p no:cacheprovider
